name: Codeco Workflow Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Testing Workflow
      run: echo Hello everyone!