name: CoderCo Custom Action Combined

on: [push]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
  
    - name: hello world custome actions
      uses: sss-3333/coderco-customaction-lab@main
      with:
        who-to-greet: 'safaa'

